uint64 timestamp          # time since system start (microseconds)
uint64 timestamp_sample

float32 res_roll		  # residual roll, pitch and yaw angles (estimated value - sensor value)
float32 res_pitch
float32 res_yaw

float32 res_roll_rate	  # residual roll, pitch and yaw rates (estimated value - sensor value)
float32 res_pitch_rate
float32 res_yaw_rate

float32 res_x_pos	  # residual x, y and z positions (estimated value - sensor value)
float32 res_y_pos
float32 res_z_pos

uint8 ORB_QUEUE_LENGTH = 8



